### ISSUE TITLE
Unable to compile with coq 8.12.0 and 8.13.0

### ISSUE THREAD

**Issue by yonathanF** [damien-pous/relation-algebra#21]
Hi! I'm trying to get up and running with this library. I installed it following the README and opam shows coq as version 8.12.0 and coq-relation-algebra as 1.7.4. I have also tried versions 8.13.0 and 1.7.5. I tried running `imp.v` but it fails at the require import line with:

```
Unable to locate library kat. (While searching for a .vos file.)
```

Running make produces the following error:

```ml
File "ra_common.ml", line 92, characters 51-107:
Error: This expression has type
         < constant : 'a; dterm : 'b; level : 'c; name : 'd; pattern : 'e;
           reference : 'f; tacexpr : 'g; term : 'h >
         Ltac_plugin.Tacexpr.gen_tactic_arg
       but an expression was expected of type
         < constant : 'i; dterm : 'j; level : 'k; name : 'l; pattern : 'm;
           reference : 'n; tacexpr : 'o; term : 'p >
         Ltac_plugin.Tacexpr.gen_tactic_arg CAst.t
make[1]: *** [Makefile.coq:668: ra_common.cmx] Error 2
make: *** [Makefile.coq:343: all] Error 2
```
Any ideas on how to go about fixing this? Thanks!

**Comment by damien-pous** [comment]
Hi,

The compilation error looks like you are compiling a version of the library
with a incompatible version of Coq (e.g., 1.7.4 with Coq 8.13, or 1.7.5
with Coq 8.12).
Since you seem to be using opam, why don't you install the library with
opam?

opam install coq-relation-algebra
(this should work whatever the installed version of Coq)

Then, if you want to 'run' imp.v or a modified version of it, you probably
have to replace the appropriate Require Import line with

From RelationAlgebra Require Import kat prop rel comparisons kat_tac.

Best,
Damien




Le ven. 13 août 2021 à 03:46, Yonathan Fisseha ***@***.***> a
écrit :

**Comment by yonathanF** [comment]
Thanks. I'm new to Coq and didn't think to check where it was looking for imports. Adding the `From RelationAlgebra` fixed my issue.
